name: Check flake

on:
  push:
    branches:
      - main
    paths:
      - '**/*.nix'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_on_tmpfs: true
      - name: Cache Nix store paths
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Flake output checks
        run: nix flake check -L --option keep-going true
