name: publish docs

on:
  push:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build docs
        run: |
          nix build .#docs --print-build-logs
      - name: Create documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: result

  docs-deploy:
    needs: docs-build
    runs-on: ubuntu-latest
    # needs access to the id and pages to push automatically
    permissions: 
      contents: write
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:   
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4